In [1]:
import sys
sys.path.append("../src")

import pandas as pd

from processing.pro_football_reference_cleaner import clean_data as pfr_cleaner
from processing.nfl_data_py_cleaner import clean_data as ndp_cleaner

In [2]:
pfr = []
for season in range(2010, 2025):
    temp_df = pd.read_json(f"../data/raw/pro_football_reference_{season}.json")
    pfr.append(temp_df)
pfr = pd.concat(pfr, ignore_index=True)
pfr = pfr_cleaner(pfr)

pfr

,game_id,home_team,away_team,roof,surface,attendance,home_line,over_under,home_pbp_exp_points_tot,home_pbp_exp_points_off_tot,...,away_sacks,away_sack_yards,away_fumbles,away_fumbles_lost,away_penalties,away_penalties_yds,away_third_down_conversions,away_third_down_attempts,away_fourth_down_conversions,away_fourth_down_attempts
0,20100909_min_nor,nor,min,indoors,turf,70051.0,-5.0,49.5,5.0,2.86,...,1,9,1,0,6,60,5,13,0,0
1,20100912_mia_buf,buf,mia,outdoors,turf,69295.0,3.0,39.0,-5.0,-10.47,...,3,18,0,0,3,15,8,18,0,0
2,20100912_det_chi,chi,det,outdoors,grass,62080.0,-6.5,45.0,4.0,-9.47,...,2,23,3,2,7,40,4,14,0,1
3,20100912_clt_htx,htx,clt,indoors,grass,70974.0,1.0,48.0,10.0,17.43,...,2,14,1,1,5,73,4,12,1,1
4,20100912_cin_nwe,nwe,cin,outdoors,turf,68756.0,-5.5,45.0,14.0,15.94,...,1,4,2,1,2,5,8,15,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4073,20250119_ram_phi,phi,ram,outdoors,grass,69879.0,-6.5,42.0,6.0,7.76,...,5,33,3,2,3,30,6,16,1,2
4074,20250119_rav_buf,buf,rav,outdoors,None,70697.0,1.0,51.0,4.0,10.81,...,2,14,3,2,5,43,7,10,1,1
4075,20250126_was_phi,phi,was,outdoors,grass,69879.0,-6.0,47.5,34.0,34.18,...,3,27,3,3,9,47,7,17,4,6
4076,20250126_buf_kan,kan,buf,outdoors,grass,73487.0,-1.5,48.5,3.0,18.77,...,2,10,4,0,6,48,5,14,4,6
4077,20250209_kan_phi,phi,kan,indoors,turf,65719.0,1.0,48.5,21.0,3.33,...,6,31,2,1,7,75,3,11,0,1

In [3]:
ndp = pd.read_csv("../data/raw/nfl_data_py_2010.csv", low_memory=False)
ndp = ndp_cleaner(ndp)

ndp

,game_id,home_final_score,away_final_score,season,week,home_drive_nunique_off,home_epa_sum_off,home_epa_mean_off,home_wp_mean_off,home_score_differential_mean_off,...,away_qb_dropback_sum_def,away_qb_scramble_sum_def,away_first_down_rush_sum_def,away_receiving_yards_sum_def,away_receiving_yards_mean_def,away_yards_after_catch_sum_def,away_yards_after_catch_mean_def,away_tackled_for_loss_sum_def,away_qb_hit_sum_def,away_sack_sum_def
0,20100912_mia_buf,10.0,15.0,2010,1,12,-9.347808,-0.126322,0.273982,-6.302632,...,39.0,2.0,3.0,139.0,7.722222,44.0,2.444444,5.0,8.0,3.0
1,20100912_det_chi,19.0,14.0,2010,1,15,-13.467760,-0.146389,0.553132,-1.569892,...,44.0,5.0,4.0,372.0,16.173913,220.0,9.565217,2.0,7.0,4.0
2,20100912_clt_htx,34.0,23.0,2010,1,11,17.606223,0.222864,0.823663,6.362500,...,19.0,0.0,15.0,107.0,11.888889,50.0,5.555556,1.0,4.0,2.0
3,20100912_den_jax,24.0,17.0,2010,1,11,12.027530,0.167049,0.629177,1.513889,...,24.0,2.0,9.0,170.0,10.625000,52.0,3.250000,1.0,5.0,1.0
4,20100913_sdg_kan,21.0,14.0,2010,1,13,-9.471815,-0.143512,0.741421,5.910448,...,22.0,0.0,5.0,68.0,6.800000,35.0,3.500000,2.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,20110116_nyj_nwe,20.0,28.0,2010,19,12,-1.362539,-0.014495,0.307005,-7.127660,...,50.0,0.0,6.0,299.0,10.310345,177.0,6.103448,2.0,7.0,5.0
263,20110115_rav_pit,31.0,24.0,2010,19,13,-4.174260,-0.045372,0.463197,-4.698925,...,40.0,2.0,7.0,226.0,11.894737,84.0,4.421053,3.0,6.0,6.0
264,20110123_gnb_chi,14.0,21.0,2010,20,14,-13.627863,-0.160328,0.179976,-10.894118,...,43.0,3.0,5.0,233.0,12.263158,117.0,6.157895,3.0,5.0,2.0
265,20110123_nyj_pit,24.0,18.0,2010,20,9,7.300539,0.093597,0.815263,7.936709,...,26.0,5.0,10.0,133.0,13.300000,55.0,5.500000,3.0,2.0,2.0
266,20110206_pit_gnb,31.0,25.0,2010,21,12,4.410572,0.058808,0.780875,5.131579,...,42.0,0.0,4.0,304.0,12.666667,86.0,3.583333,1.0,8.0,3.0

In [6]:
tst = pfr.merge(ndp, on="game_id")
tst

,game_id,home_team,away_team,roof,surface,attendance,home_line,over_under,home_pbp_exp_points_tot,home_pbp_exp_points_off_tot,...,away_qb_dropback_sum_def,away_qb_scramble_sum_def,away_first_down_rush_sum_def,away_receiving_yards_sum_def,away_receiving_yards_mean_def,away_yards_after_catch_sum_def,away_yards_after_catch_mean_def,away_tackled_for_loss_sum_def,away_qb_hit_sum_def,away_sack_sum_def
0,20100909_min_nor,nor,min,indoors,turf,70051.0,-5.0,49.5,5.00,2.86,...,37.0,0.0,6.0,237.0,8.777778,124.0,4.592593,3.0,2.0,1.0
1,20100912_mia_buf,buf,mia,outdoors,turf,69295.0,3.0,39.0,-5.00,-10.47,...,39.0,2.0,3.0,139.0,7.722222,44.0,2.444444,5.0,8.0,3.0
2,20100912_det_chi,chi,det,outdoors,grass,62080.0,-6.5,45.0,4.00,-9.47,...,44.0,5.0,4.0,372.0,16.173913,220.0,9.565217,2.0,7.0,4.0
3,20100912_clt_htx,htx,clt,indoors,grass,70974.0,1.0,48.0,10.00,17.43,...,19.0,0.0,15.0,107.0,11.888889,50.0,5.555556,1.0,4.0,2.0
4,20100912_cin_nwe,nwe,cin,outdoors,turf,68756.0,-5.5,45.0,14.00,15.94,...,35.0,0.0,7.0,258.0,10.320000,177.0,7.080000,1.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,20110116_sea_chi,chi,sea,outdoors,grass,62265.0,-10.0,43.0,11.00,9.08,...,34.0,2.0,11.0,274.0,18.266667,135.0,9.000000,2.0,4.0,3.0
263,20110116_nyj_nwe,nwe,nyj,outdoors,turf,68756.0,-9.5,45.0,-6.40,-6.26,...,50.0,0.0,6.0,299.0,10.310345,177.0,6.103448,2.0,7.0,5.0
264,20110123_gnb_chi,chi,gnb,outdoors,grass,62377.0,3.5,42.5,-7.00,-14.09,...,43.0,3.0,5.0,233.0,12.263158,117.0,6.157895,3.0,5.0,2.0
265,20110123_nyj_pit,pit,nyj,outdoors,grass,66662.0,-4.0,38.0,3.34,4.42,...,26.0,5.0,10.0,133.0,13.300000,55.0,5.500000,3.0,2.0,2.0
266,20110206_pit_gnb,gnb,pit,indoors,turf,103219.0,-3.0,45.0,6.96,7.72,...,42.0,0.0,4.0,304.0,12.666667,86.0,3.583333,1.0,8.0,3.0